### ISSUE TITLE
Obviously state what fat jar is

### ISSUE THREAD

**Issue by KosmX** [KosmX/jneedle#36]

**Comment by Twisted-Code** [comment]
*looks at issue timestamp, 10 minutes ago* let me guess, you got some questions about this as a result of MPAA's announcement earlier?
I was about to ask, then I realized it probably meant (and please correct me if I'm wrong) a version of the jar that has everything built-in, no JIT download? (I don't do a lot of Java, this is just a very poor educated guess)

**Comment by KosmX** [comment]
No, in Java, fat jars mean that it has all dependency included in the jar file, simple (non-fat) jar does not have all required dependency included.  
fat jars are often called standalone as those can be used simply by `java -jar ...`, non-fat (or slim) are meant for embedding those as a library in another program.

**Comment by KosmX** [comment]
By the way, your guess is right about MMPA.
