### ISSUE TITLE
Clarification of usage / Quickstart

### ISSUE THREAD

**Issue by FGBxRamel** [KosmX/jneedle#43]
Hey!

I just used it, great program!
Since I had some troubles starting, I would recommend making a clear "Quickstart" section at the top of the ReadMe.
I would do it if PRs that don't change the Java/Kotlin code are welcome?
Thanks in advance.

**Comment by KosmX** [comment]
Hi,

Any help, all PRs are welcome!

**Comment by KosmX** [comment]
If you do a PR editing the readme, please try to modify only that (if you don't need to change program source files, don't change those)

Thanks for the help

**Comment by FGBxRamel** [comment]
Do you want/need [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?

**Comment by KosmX** [comment]
That's not a bad idea.

> if possible, open a different PR for the readme fix and for this.

**Comment by FGBxRamel** [comment]
I will use conventional commits then.

> if possible, open a different PR for the readme fix and for this.

What do you mean? I will open a PR for the quickstart addition. Anything else (not Java related) that you need help with?
